apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kandji-cloudflare-syncer.fullname" . }}-secrets
  labels:
    {{- include "kandji-cloudflare-syncer.labels" . | nindent 4 }}
type: Opaque
data:
  KANDJI_API_TOKEN: {{ .Values.secretEnv.KANDJI_API_TOKEN | b64enc | quote }}
  CLOUDFLARE_API_TOKEN: {{ .Values.secretEnv.CLOUDFLARE_API_TOKEN | b64enc | quote }}
